### PR TITLE
Joe search front

### PR DESCRIPTION
**Pull request by LesterCodingMaster**
So I had a hard time when I tried to pull and merge this back into the original.
So what I had to do was start over and clone it, but I kept my old file open, and I copied a lot of the files that I had made and put in here so that's why it shows there's a bunch of stuff changed but in reality I didn't change every file lol
But check this out and see if this search will work and I will continue working on it.
For some reason the RSS feed was not working for me for some reason, maybe that is not implemented yet in the dev, but I wasn't sure.

### CODE REVIEW

**Comment by LesterCodingMaster** [comment]
It's showing that it has conflict in the navigation and RSS feed

**Comment by LesterCodingMaster** [comment]
I believe this will work if y'all want to take a look at it and let me know thank you

**Comment by LesterCodingMaster** [comment]
Please review this and let me know if it works for y'all. Check your slack for video

**Review by Carlito-Pedida — APPROVED** [review]
Looks good Joe!

**Pull request merged**
